baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Udula Dewmina Kaveeshwara
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv/
          weight: 1
        - name: Contact
          url: contact/
          weight: 2

params:
    description: "Portfolio website of Udula Dewmina Kaveeshwara - Software Development Student."
    author: Udula Dewmina Kaveeshwara
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["cv"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Udula Dewmina Kaveeshwara
          subtitle: "Software Development student currently following a Higher National Diploma (HND) in Technology. Specializing in Software Development, passionate about learning new technologies, sports, and team activities."
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: CV
              url: cv/
            - name: Contact
              url: contact/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:uduladewminak@gmail.com
        - name: GitHub
          url: https://github.com/Dewmina892

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Udula Dewmina Kaveeshwara"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2